name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.5.7  #  Node.js version

    - name: Install dependencies and build
      working-directory: ./frontend  # frontend folder
      run: |
        npm ci  
        npm run build  

    - name: Run tests
      working-directory: ./frontend
      run: npm test